source "http://rubygems.org"
gem "yajl-ruby"
gem "sinatra"
gem "rack"
gem "unicorn"
gem "haml"
gem "memcached"
gem "sass"
gem "thor"
gem "data_mapper"
gem "dm-postgres-adapter"
gem "dm-postgis"
gem "GeoRuby"
gem "rack-cache"
gem "color-tools"
gem "builder"
gem "em-websocket"
gem "activesupport"
gem "i18n"

# Useful some day
# gem "memcache-client"
# gem "amatch"
# gem "unicode"
# gem "i18n"

group :development, :test do
  gem "shotgun"
  gem "coffee-script"
  gem "nokogiri"
  gem "capistrano"
  gem "awesome_print"
  gem "growl"
  gem "gexf"
  gem "unicode_utils"
  gem "mechanize"
  gem "amatch"
end
